# Use docker-based build environment (instead of openvz)
dist: trusty
sudo: false

language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - oraclejdk-ea
  - openjdk10
  - openjdk11
script: ./gradlew check benchmark
