# Use docker-based build environment (instead of openvz)
dist: trusty
sudo: false

language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk10
  - openjdk10
  - openjdk11
  - openjdk-ea

matrix:
  include:
    - jdk: openjdk11
      before_install: &fix_certs
        - rm "${JAVA_HOME}/lib/security/cacerts"
        - ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"
    - jdk: openjdk-ea
      before_install: *fix_certs

script: ./gradlew check benchmark
