# Use docker-based build environment (instead of openvz)
# sudo: false

# for oraclejdk9
sudo: required
dist: trusty
group: edge

language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - oraclejdk9
script: gradle check benchmark
